"""
Django settings for deep_engine_client project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from .base import *

env = os.environ.get('DME_ENV', None)
print(f"DME_EMV : {env}")
if env == 'prod':
    from .prod import *
    RUNTIME_ENV = 'prod'
else:
    from .test import *
    RUNTIME_ENV = 'test'
